"""Dagster definition loader for Sling based ingestion assets."""

from dagster import Definitions
from dagster.components import definitions


@definitions
def defs() -> Definitions:
    """Construct the Sling specific Dagster ``Definitions`` bundle.

    Returns:
        dagster.Definitions: Definitions generated by :class:`DagsterSlingFactory`
        using the YAML configuration located under the Sling config directory.
    """
    from pathlib import Path

    from .factory import DagsterSlingFactory

    # Resolve the root folder containing Sling YAML configuration files.
    config_dir = Path(__file__).joinpath(*[".."], "sling").resolve()

    return DagsterSlingFactory.build_definitions(config_dir)
