-- ANALYTICS AND ENGINEERING ROLES
CREATE ROLE IF NOT EXISTS ANALYTICS_USER;
CREATE ROLE IF NOT EXISTS DATA_ANALYST;
CREATE ROLE IF NOT EXISTS DATA_ENGINEER;
CREATE ROLE IF NOT EXISTS ANALYTICS_ENGINEER;


GRANT USAGE ON DATABASE ANALYTICS TO ANALYTICS_USER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE ANALYTICS TO ANALYTICS_USER;
GRANT SELECT ON ALL TABLES IN DATABASE ANALYTICS TO ANALYTICS_USER;

CREATE ROLE IF NOT EXISTS ANALYTICS_DEVELOPER;
GRANT ROLE ANALYTICS_USER TO ROLE ANALYTICS_DEVELOPER;
GRANT USAGE ON DATABASE _DEV_ANALYTICS TO ANALYTICS_DEVELOPER;
GRANT CREATE SCHEMA ON DATABASE _DEV_ANALYTICS TO ANALYTICS_DEVELOPER


CREATE ROLE IF NOT EXISTS RAW_DEVELOPER;
GRANT ROLE ANALYTICS_DEVELOPER TO ROLE RAW_DEVELOPER;
GRANT USAGE ON DATABASE _DEV_RAW TO RAW_DEVELOPER;
GRANT CREATE SCHEMA ON DATABASE _DEV_RAW TO RAW_DEVELOPER;





CREATE ROLE IF NOT EXISTS MARKETING;
CREATE ROLE IF NOT EXISTS FINANCE;
CREATE ROLE IF NOT EXISTS FOUNDATION;
GRANT ROLE ANALYTICS_DEVELOPER TO ROLE DATA_ANALYST;
GRANT ROLE RAW_DEVELOPER TO ROLE DATA_ENGINEER;
GRANT ROLE RAW_DEVELOPER TO ROLE ANALYTICS_ENGINEER;

GRANT ROLE DATA_ENGINEER TO USER ASTAUS;