----------------------------------
-- ROLES ----------------------------------
----------------------------------
---- UBAC
CREATE ROLE IF NOT EXISTS MARKETING_DATA_ANALYST; -- Has access to general and marketing
CREATE ROLE IF NOT EXISTS FINANCE_DATA_ANALYST; -- Has access to general and finance

CREATE ROLE IF NOT EXISTS ANALYTICS_ENGINEER; -- Has access to all analytics
CREATE ROLE IF NOT EXISTS DATA_ENGINEER; -- Has access to all analytics and raw

CREATE ROLE IF NOT EXISTS SERVICE_PRINCIPLE; -- Has access to all

---- RBAC
CREATE ROLE IF NOT EXISTS DATA_ANALYST;
CREATE ROLE IF NOT EXISTS FOUNDATION;
CREATE ROLE IF NOT EXISTS MARKETING;
CREATE ROLE IF NOT EXISTS FINANCE;

---- INHERITENCE
GRANT ROLE DATA_ANALYST TO ROLE ANALYTICS_ENGINEER;
GRANT ROLE ANALYTICS_ENGINEER TO ROLE DATA_ENGINEER;
GRANT ROLE DATA_ENGINEER TO ROLE SERVICE_PRINCIPLE;

GRANT ROLE MARKETING TO ROLE FOUNDATION;
GRANT ROLE FINANCE TO ROLE FOUNDATION;

GRANT ROLE MARKETING TO ROLE MARKETING_DATA_ANALYST;
GRANT ROLE DATA_ANALYST TO ROLE MARKETING_DATA_ANALYST;

GRANT ROLE FINANCE TO ROLE FINANCE_DATA_ANALYST;
GRANT ROLE DATA_ANALYST TO ROLE FINANCE_DATA_ANALYST;

GRANT ROLE FOUNDATION TO ROLE ANALYTICS_ENGINEER;
GRANT ROLE FOUNDATION TO ROLE DATA_ENGINEER;
GRANT ROLE FOUNDATION TO ROLE SERVICE_PRINCIPLE;


----------------------------------
-- USERS ---------------------------------------
----------------------------------
-- SERVICE ACCOUNTS
CREATE USER IF NOT EXISTS DATA_PLATFORM;

-- USER ACCOUNTS
CREATE USER IF NOT EXISTS ASTAUS;
CREATE USER IF NOT EXISTS JSMITH;

---- UBAC GRANTS
GRANT ROLE DATA_ENGINEER TO USER ASTAUS;
GRANT ROLE MARKETING_DATA_ANALYST TO USER JSMITH;
GRANT ROLE SERVICE_PRINCIPLE TO USER DATA_PLATFORM;

---- DEFAULT WAREHOUSE
ALTER USER ASTAUS SET DEFAULT_WAREHOUSE = COMPUTE_WH;
ALTER USER DATA_PLATFORM SET DEFAULT_WAREHOUSE = COMPUTE_WH;


----------------------------------
-- WAREHOUSES ----------------------------------
----------------------------------
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE DATA_ANALYST;


----------------------------------
-- DATABASES -----------------------------------
----------------------------------
DROP DATABASE IF EXISTS SNOWFLAKE_LEARNING_DB;
DROP DATABASE IF EXISTS SNOWFLAKE_SAMPLE_DATA;

---- PROD
------ ANALYTICS
CREATE DATABASE IF NOT EXISTS ANALYTICS;

GRANT USAGE ON DATABASE ANALYTICS TO DATA_ANALYST;
GRANT USAGE ON ALL SCHEMAS IN DATABASE ANALYTICS TO DATA_ANALYST;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE ANALYTICS TO DATA_ANALYST;
GRANT SELECT ON ALL TABLES IN DATABASE ANALYTICS TO DATA_ANALYST;
GRANT SELECT ON FUTURE TABLES IN DATABASE ANALYTICS TO DATA_ANALYST;
GRANT CREATE SCHEMA ON DATABASE ANALYTICS TO ROLE SERVICE_PRINCIPLE;

------ RAW
CREATE DATABASE IF NOT EXISTS RAW;

GRANT USAGE ON DATABASE RAW TO DATA_ENGINEER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE RAW TO DATA_ENGINEER;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE RAW TO DATA_ENGINEER;
GRANT SELECT ON ALL TABLES IN DATABASE RAW TO DATA_ENGINEER;
GRANT SELECT ON FUTURE TABLES IN DATABASE RAW TO DATA_ENGINEER;
GRANT CREATE SCHEMA ON DATABASE RAW TO ROLE SERVICE_PRINCIPLE;

------ SNAPSHOTS
CREATE DATABASE IF NOT EXISTS SNAPSHOTS;

GRANT USAGE ON DATABASE SNAPSHOTS TO DATA_ENGINEER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE SNAPSHOTS TO DATA_ENGINEER;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE SNAPSHOTS TO DATA_ENGINEER;
GRANT SELECT ON ALL TABLES IN DATABASE SNAPSHOTS TO DATA_ENGINEER;
GRANT SELECT ON FUTURE TABLES IN DATABASE SNAPSHOTS TO DATA_ENGINEER;
GRANT CREATE SCHEMA ON DATABASE SNAPSHOTS TO ROLE SERVICE_PRINCIPLE;

---- DEV
------ _DEV_ANALYTICS
CREATE DATABASE IF NOT EXISTS _DEV_ANALYTICS;
GRANT USAGE ON DATABASE _DEV_ANALYTICS TO DATA_ANALYST;
GRANT CREATE SCHEMA ON DATABASE _DEV_ANALYTICS TO ROLE DATA_ANALYST;

------ _DEV_RAW
CREATE DATABASE IF NOT EXISTS _DEV_RAW;
GRANT USAGE ON DATABASE _DEV_RAW TO DATA_ENGINEER;
GRANT CREATE SCHEMA ON DATABASE _DEV_RAW TO ROLE DATA_ENGINEER;

------ _DEV_SNAPS
CREATE DATABASE IF NOT EXISTS _DEV_SNAPSHOTS;
GRANT USAGE ON DATABASE _DEV_SNAPSHOTS TO DATA_ENGINEER;
GRANT CREATE SCHEMA ON DATABASE _DEV_SNAPSHOTS TO ROLE DATA_ENGINEER;


----------------------------------
-- FLUSH DEV ----------------------------------
----------------------------------
-- CREATE OR REPLACE DATABASE _DEV_ANALYTICS;
-- GRANT USAGE ON DATABASE _DEV_ANALYTICS TO ROLE ANALYTICS_DEVELOPER;
-- GRANT CREATE SCHEMA ON DATABASE _DEV_ANALYTICS TO ROLE ANALYTICS_DEVELOPER;

-- CREATE OR REPLACE DATABASE _DEV_RAW;
-- GRANT USAGE ON DATABASE _DEV_RAW TO ROLE ANALYTICS_DEVELOPER;
-- GRANT CREATE SCHEMA ON DATABASE _DEV_RAW TO ROLE ANALYTICS_DEVELOPER;
